// Mocks generated by Mockito 5.0.15 from annotations
// in hatchery/test/features/signin/presentation/bloc/secret/sign_in_secret_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i6;
import 'package:dartz/dartz.dart' as _i5;
import 'package:hatchery/core/shared_kernel/shared_kernel.dart' as _i10;
import 'package:hatchery/features/authorization/presentation/bloc/auth_bloc.dart'
    as _i2;
import 'package:hatchery/features/signin/domain/entities/value_objects.dart'
    as _i12;
import 'package:hatchery/features/signin/domain/services/auth_failure.dart'
    as _i11;
import 'package:hatchery/features/signin/domain/usecases/sign_in_with_secret.dart'
    as _i9;
import 'package:hatchery/features/signin/presentation/bloc/secret/reset/sign_in_secret_reset_bloc.dart'
    as _i4;
import 'package:hatchery/features/signin/presentation/manager/navigation.manager.dart'
    as _i7;
import 'package:hatchery/features/signin/presentation/routes/sign_in_go_to.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAuthState_0 extends _i1.Fake implements _i2.AuthState {}

class _FakeStreamSubscription_1<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

class _FakeSignInSecretResetState_2 extends _i1.Fake
    implements _i4.SignInSecretResetState {}

class _FakeEither_3<L, R> extends _i1.Fake implements _i5.Either<L, R> {}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i2.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeAuthState_0()) as _i2.AuthState);
  @override
  _i3.Stream<_i2.AuthState> get stream => (super.noSuchMethod(
      Invocation.getter(#stream),
      returnValue: Stream<_i2.AuthState>.empty()) as _i3.Stream<_i2.AuthState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i3.Stream<_i2.AuthState> mapEventToState(_i2.AuthEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.AuthState>.empty())
          as _i3.Stream<_i2.AuthState>);
  @override
  void add(_i2.AuthEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.AuthEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>> transformEvents(
          _i3.Stream<_i2.AuthEvent>? events,
          _i6.TransitionFunction<_i2.AuthEvent, _i2.AuthState>? transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>>.empty())
          as _i3.Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>>);
  @override
  void emit(_i2.AuthState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(_i6.Transition<_i2.AuthEvent, _i2.AuthState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>> transformTransitions(
          _i3.Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>>?
              transitions) =>
      (super.noSuchMethod(
              Invocation.method(#transformTransitions, [transitions]),
              returnValue:
                  Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>>.empty())
          as _i3.Stream<_i6.Transition<_i2.AuthEvent, _i2.AuthState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i2.AuthState> listen(
          void Function(_i2.AuthState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_1<_i2.AuthState>())
          as _i3.StreamSubscription<_i2.AuthState>);
  @override
  void onChange(_i6.Change<_i2.AuthState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SignInSecretResetBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInSecretResetBloc extends _i1.Mock
    implements _i4.SignInSecretResetBloc {
  MockSignInSecretResetBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SignInSecretResetState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeSignInSecretResetState_2())
          as _i4.SignInSecretResetState);
  @override
  _i3.Stream<_i4.SignInSecretResetState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.SignInSecretResetState>.empty())
          as _i3.Stream<_i4.SignInSecretResetState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i3.Stream<_i4.SignInSecretResetState> mapEventToState(
          _i4.SignInSecretResetEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i4.SignInSecretResetState>.empty())
          as _i3.Stream<_i4.SignInSecretResetState>);
  @override
  void add(_i4.SignInSecretResetEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.SignInSecretResetEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>
      transformEvents(
              _i3.Stream<_i4.SignInSecretResetEvent>? events,
              _i6.TransitionFunction<_i4.SignInSecretResetEvent,
                      _i4.SignInSecretResetState>?
                  transitionFn) =>
          (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>.empty()) as _i3
              .Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>);
  @override
  void emit(_i4.SignInSecretResetState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i6.Transition<_i4.SignInSecretResetEvent,
                  _i4.SignInSecretResetState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>
      transformTransitions(
              _i3.Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>.empty())
              as _i3.Stream<
                  _i6.Transition<_i4.SignInSecretResetEvent, _i4.SignInSecretResetState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i4.SignInSecretResetState> listen(
          void Function(_i4.SignInSecretResetState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue:
                  _FakeStreamSubscription_1<_i4.SignInSecretResetState>())
          as _i3.StreamSubscription<_i4.SignInSecretResetState>);
  @override
  void onChange(_i6.Change<_i4.SignInSecretResetState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NavigationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationManager extends _i1.Mock implements _i7.NavigationManager {
  MockNavigationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i8.SignInPageGoTo> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i8.SignInPageGoTo>.empty())
          as _i3.Stream<_i8.SignInPageGoTo>);
  @override
  void goTo(_i8.SignInPageGoTo? parameters) =>
      super.noSuchMethod(Invocation.method(#goTo, [parameters]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SignInWithSecret].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithSecret extends _i1.Mock implements _i9.SignInWithSecret {
  MockSignInWithSecret() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Either<_i10.FailureDetails<_i11.AuthFailure>, _i5.Unit>> call(
          _i12.Secret? secret) =>
      (super.noSuchMethod(Invocation.method(#call, [secret]),
          returnValue:
              Future<_i5.Either<_i10.FailureDetails<_i11.AuthFailure>, _i5.Unit>>.value(
                  _FakeEither_3<_i10.FailureDetails<_i11.AuthFailure>,
                      _i5.Unit>())) as _i3
          .Future<_i5.Either<_i10.FailureDetails<_i11.AuthFailure>, _i5.Unit>>);
  @override
  String toString() => super.toString();
}
