// Mocks generated by Mockito 5.0.15 from annotations
// in vethx_beta/test/core/services/cache.service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:typed_data' as _i11;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hive/hive.dart' as _i3;
import 'package:hive/src/box/default_compaction_strategy.dart' as _i10;
import 'package:hive/src/box/default_key_comparator.dart' as _i9;
import 'package:hive/src/hive_impl.dart' as _i8;
import 'package:hive/src/registry/type_registry_impl.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vethx_beta/core/error/failures.dart' as _i5;
import 'package:vethx_beta/core/services/storage/i_local_storage.service.dart'
    as _i6;
import 'package:vethx_beta/core/services/storage/pii.service.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeBox_1<E> extends _i1.Fake implements _i3.Box<E> {}

class _FakeLazyBox_2<E> extends _i1.Fake implements _i3.LazyBox<E> {}

/// A class which mocks [PII].
///
/// See the documentation for Mockito's code generation for more information.
class MockPII extends _i1.Mock implements _i4.PII {
  MockPII() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<_i5.Failure, String> getKey(
          _i6.PersonallyIdentifiableInformationKeys? key) =>
      (super.noSuchMethod(Invocation.method(#getKey, [key]),
              returnValue: _FakeEither_0<_i5.Failure, String>())
          as _i2.Either<_i5.Failure, String>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, String>> get(
          {_i6.PersonallyIdentifiableInformationKeys? key}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#key: key}),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i7.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, _i2.Unit>> remove(
          {_i6.PersonallyIdentifiableInformationKeys? key}) =>
      (super.noSuchMethod(Invocation.method(#remove, [], {#key: key}),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>()))
          as _i7.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, _i2.Unit>> write(
          {_i6.PersonallyIdentifiableInformationKeys? key, String? obj}) =>
      (super.noSuchMethod(Invocation.method(#write, [], {#key: key, #obj: obj}),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>()))
          as _i7.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i3.Box<E> {
  @override
  Iterable<E> get values =>
      (super.noSuchMethod(Invocation.getter(#values), returnValue: <E>[])
          as Iterable<E>);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);
  @override
  bool get lazy =>
      (super.noSuchMethod(Invocation.getter(#lazy), returnValue: false)
          as bool);
  @override
  Iterable<dynamic> get keys =>
      (super.noSuchMethod(Invocation.getter(#keys), returnValue: <dynamic>[])
          as Iterable<dynamic>);
  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);
  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  Iterable<E> valuesBetween({dynamic startKey, dynamic endKey}) =>
      (super.noSuchMethod(
          Invocation.method(
              #valuesBetween, [], {#startKey: startKey, #endKey: endKey}),
          returnValue: <E>[]) as Iterable<E>);
  @override
  E? getAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#getAt, [index])) as E?);
  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(Invocation.method(#toMap, []),
      returnValue: <dynamic, E>{}) as Map<dynamic, E>);
  @override
  String toString() => super.toString();
  @override
  dynamic keyAt(int? index) =>
      super.noSuchMethod(Invocation.method(#keyAt, [index]));
  @override
  _i7.Stream<_i3.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
      Invocation.method(#watch, [], {#key: key}),
      returnValue: Stream<_i3.BoxEvent>.empty()) as _i7.Stream<_i3.BoxEvent>);
  @override
  bool containsKey(dynamic key) =>
      (super.noSuchMethod(Invocation.method(#containsKey, [key]),
          returnValue: false) as bool);
  @override
  _i7.Future<void> put(dynamic key, E? value) =>
      (super.noSuchMethod(Invocation.method(#put, [key, value]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> putAt(int? index, E? value) =>
      (super.noSuchMethod(Invocation.method(#putAt, [index, value]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> putAll(Map<dynamic, E>? entries) =>
      (super.noSuchMethod(Invocation.method(#putAll, [entries]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<int> add(E? value) =>
      (super.noSuchMethod(Invocation.method(#add, [value]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Iterable<int>> addAll(Iterable<E>? values) =>
      (super.noSuchMethod(Invocation.method(#addAll, [values]),
              returnValue: Future<Iterable<int>>.value(<int>[]))
          as _i7.Future<Iterable<int>>);
  @override
  _i7.Future<void> delete(dynamic key) =>
      (super.noSuchMethod(Invocation.method(#delete, [key]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> deleteAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#deleteAt, [index]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> deleteAll(Iterable<dynamic>? keys) =>
      (super.noSuchMethod(Invocation.method(#deleteAll, [keys]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> compact() =>
      (super.noSuchMethod(Invocation.method(#compact, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<int> clear() => (super.noSuchMethod(Invocation.method(#clear, []),
      returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> deleteFromDisk() =>
      (super.noSuchMethod(Invocation.method(#deleteFromDisk, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
}

/// A class which mocks [HiveImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveImpl extends _i1.Mock implements _i8.HiveImpl {
  @override
  set homePath(String? _homePath) =>
      super.noSuchMethod(Invocation.setter(#homePath, _homePath),
          returnValueForMissingStub: null);
  @override
  void init(String? path) =>
      super.noSuchMethod(Invocation.method(#init, [path]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<_i3.Box<E>> openBox<E>(String? name,
          {_i3.HiveCipher? encryptionCipher,
          _i3.KeyComparator? keyComparator = _i9.defaultKeyComparator,
          _i3.CompactionStrategy? compactionStrategy =
              _i10.defaultCompactionStrategy,
          bool? crashRecovery = true,
          String? path,
          _i11.Uint8List? bytes,
          List<int>? encryptionKey}) =>
      (super.noSuchMethod(
              Invocation.method(#openBox, [
                name
              ], {
                #encryptionCipher: encryptionCipher,
                #keyComparator: keyComparator,
                #compactionStrategy: compactionStrategy,
                #crashRecovery: crashRecovery,
                #path: path,
                #bytes: bytes,
                #encryptionKey: encryptionKey
              }),
              returnValue: Future<_i3.Box<E>>.value(_FakeBox_1<E>()))
          as _i7.Future<_i3.Box<E>>);
  @override
  _i7.Future<_i3.LazyBox<E>> openLazyBox<E>(String? name,
          {_i3.HiveCipher? encryptionCipher,
          _i3.KeyComparator? keyComparator = _i9.defaultKeyComparator,
          _i3.CompactionStrategy? compactionStrategy =
              _i10.defaultCompactionStrategy,
          bool? crashRecovery = true,
          String? path,
          List<int>? encryptionKey}) =>
      (super.noSuchMethod(
              Invocation.method(#openLazyBox, [
                name
              ], {
                #encryptionCipher: encryptionCipher,
                #keyComparator: keyComparator,
                #compactionStrategy: compactionStrategy,
                #crashRecovery: crashRecovery,
                #path: path,
                #encryptionKey: encryptionKey
              }),
              returnValue: Future<_i3.LazyBox<E>>.value(_FakeLazyBox_2<E>()))
          as _i7.Future<_i3.LazyBox<E>>);
  @override
  _i3.BoxBase<dynamic>? getBoxWithoutCheckInternal(String? name) => (super
          .noSuchMethod(Invocation.method(#getBoxWithoutCheckInternal, [name]))
      as _i3.BoxBase<dynamic>?);
  @override
  _i3.Box<E> box<E>(String? name) =>
      (super.noSuchMethod(Invocation.method(#box, [name]),
          returnValue: _FakeBox_1<E>()) as _i3.Box<E>);
  @override
  _i3.LazyBox<E> lazyBox<E>(String? name) =>
      (super.noSuchMethod(Invocation.method(#lazyBox, [name]),
          returnValue: _FakeLazyBox_2<E>()) as _i3.LazyBox<E>);
  @override
  bool isBoxOpen(String? name) =>
      (super.noSuchMethod(Invocation.method(#isBoxOpen, [name]),
          returnValue: false) as bool);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void unregisterBox(String? name) =>
      super.noSuchMethod(Invocation.method(#unregisterBox, [name]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> deleteBoxFromDisk(String? name, {String? path}) =>
      (super.noSuchMethod(
          Invocation.method(#deleteBoxFromDisk, [name], {#path: path}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> deleteFromDisk() =>
      (super.noSuchMethod(Invocation.method(#deleteFromDisk, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  List<int> generateSecureKey() =>
      (super.noSuchMethod(Invocation.method(#generateSecureKey, []),
          returnValue: <int>[]) as List<int>);
  @override
  _i7.Future<bool> boxExists(String? name, {String? path}) =>
      (super.noSuchMethod(Invocation.method(#boxExists, [name], {#path: path}),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i12.ResolvedAdapter<dynamic>? findAdapterForTypeId(int? typeId) =>
      (super.noSuchMethod(Invocation.method(#findAdapterForTypeId, [typeId]))
          as _i12.ResolvedAdapter<dynamic>?);
  @override
  void registerAdapter<T>(_i3.TypeAdapter<T>? adapter,
          {bool? internal = false, bool? override = false}) =>
      super.noSuchMethod(
          Invocation.method(#registerAdapter, [adapter],
              {#internal: internal, #override: override}),
          returnValueForMissingStub: null);
  @override
  bool isAdapterRegistered(int? typeId, {bool? internal = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #isAdapterRegistered, [typeId], {#internal: internal}),
          returnValue: false) as bool);
  @override
  void resetAdapters() =>
      super.noSuchMethod(Invocation.method(#resetAdapters, []),
          returnValueForMissingStub: null);
  @override
  void ignoreTypeId<T>(int? typeId) =>
      super.noSuchMethod(Invocation.method(#ignoreTypeId, [typeId]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [HiveCipher].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveCipher extends _i1.Mock implements _i3.HiveCipher {
  @override
  int calculateKeyCrc() => (super
          .noSuchMethod(Invocation.method(#calculateKeyCrc, []), returnValue: 0)
      as int);
  @override
  int maxEncryptedSize(_i11.Uint8List? inp) =>
      (super.noSuchMethod(Invocation.method(#maxEncryptedSize, [inp]),
          returnValue: 0) as int);
  @override
  int encrypt(_i11.Uint8List? inp, int? inpOff, int? inpLength,
          _i11.Uint8List? out, int? outOff) =>
      (super.noSuchMethod(
          Invocation.method(#encrypt, [inp, inpOff, inpLength, out, outOff]),
          returnValue: 0) as int);
  @override
  int decrypt(_i11.Uint8List? inp, int? inpOff, int? inpLength,
          _i11.Uint8List? out, int? outOff) =>
      (super.noSuchMethod(
          Invocation.method(#decrypt, [inp, inpOff, inpLength, out, outOff]),
          returnValue: 0) as int);
  @override
  String toString() => super.toString();
}
