// Mocks generated by Mockito 5.0.15 from annotations
// in vethx_beta/test/features/signin/infrastructure/datasources/sign_in_local_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vethx_beta/core/error/failures.dart' as _i4;
import 'package:vethx_beta/core/services/storage/i_local_storage.service.dart'
    as _i5;
import 'package:vethx_beta/core/services/storage/pii.service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [PII].
///
/// See the documentation for Mockito's code generation for more information.
class MockPII extends _i1.Mock implements _i3.PII {
  MockPII() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<_i4.Failure, String> getKey(
          _i5.PersonallyIdentifiableInformationKeys? key) =>
      (super.noSuchMethod(Invocation.method(#getKey, [key]),
              returnValue: _FakeEither_0<_i4.Failure, String>())
          as _i2.Either<_i4.Failure, String>);
  @override
  _i6.Future<_i2.Either<_i4.Failure, String>> get(
          {_i5.PersonallyIdentifiableInformationKeys? key}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#key: key}),
              returnValue: Future<_i2.Either<_i4.Failure, String>>.value(
                  _FakeEither_0<_i4.Failure, String>()))
          as _i6.Future<_i2.Either<_i4.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i4.Failure, _i2.Unit>> remove(
          {_i5.PersonallyIdentifiableInformationKeys? key}) =>
      (super.noSuchMethod(Invocation.method(#remove, [], {#key: key}),
              returnValue: Future<_i2.Either<_i4.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i4.Failure, _i2.Unit>()))
          as _i6.Future<_i2.Either<_i4.Failure, _i2.Unit>>);
  @override
  _i6.Future<_i2.Either<_i4.Failure, _i2.Unit>> write(
          {_i5.PersonallyIdentifiableInformationKeys? key, String? obj}) =>
      (super.noSuchMethod(Invocation.method(#write, [], {#key: key, #obj: obj}),
              returnValue: Future<_i2.Either<_i4.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i4.Failure, _i2.Unit>()))
          as _i6.Future<_i2.Either<_i4.Failure, _i2.Unit>>);
  @override
  String toString() => super.toString();
}
