// Mocks generated by Mockito 5.0.14 from annotations
// in vethx_beta/test/features/signin/presentation/pages/sign_in_secret.page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vethx_beta/features/signin/presentation/bloc/secret/reset/sign_in_secret_reset_bloc.dart'
    as _i2;
import 'package:vethx_beta/features/signin/presentation/bloc/secret/sign_in_secret_bloc.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeSignInSecretResetBloc_0 extends _i1.Fake
    implements _i2.SignInSecretResetBloc {}

class _FakeSignInSecretState_1 extends _i1.Fake
    implements _i3.SignInSecretState {}

class _FakeStreamSubscription_2<T> extends _i1.Fake
    implements _i4.StreamSubscription<T> {}

/// A class which mocks [SignInSecretBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInSecretBloc extends _i1.Mock implements _i3.SignInSecretBloc {
  MockSignInSecretBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignInSecretResetBloc get secretResetBloc =>
      (super.noSuchMethod(Invocation.getter(#secretResetBloc),
              returnValue: _FakeSignInSecretResetBloc_0())
          as _i2.SignInSecretResetBloc);
  @override
  _i3.SignInSecretState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeSignInSecretState_1()) as _i3.SignInSecretState);
  @override
  _i4.Stream<_i3.SignInSecretState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.SignInSecretState>.empty())
          as _i4.Stream<_i3.SignInSecretState>);
  @override
  _i4.Stream<_i3.SignInSecretState> mapEventToState(
          _i3.SignInSecretEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i3.SignInSecretState>.empty())
          as _i4.Stream<_i3.SignInSecretState>);
  @override
  void add(_i3.SignInSecretEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.SignInSecretEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>
      transformEvents(
              _i4.Stream<_i3.SignInSecretEvent>? events,
              _i5.TransitionFunction<_i3.SignInSecretEvent, _i3.SignInSecretState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>.empty())
              as _i4.Stream<
                  _i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>);
  @override
  void emit(_i3.SignInSecretState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<_i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>
      transformTransitions(
              _i4.Stream<_i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>.empty())
              as _i4.Stream<
                  _i5.Transition<_i3.SignInSecretEvent, _i3.SignInSecretState>>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.StreamSubscription<_i3.SignInSecretState> listen(
          void Function(_i3.SignInSecretState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_2<_i3.SignInSecretState>())
          as _i4.StreamSubscription<_i3.SignInSecretState>);
  @override
  void onChange(_i5.Change<_i3.SignInSecretState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
